#!/usr/bin/env bash
# Generated by .github/scripts/generate-installers.py; edit installer.json or
# .github/installer/apply-patches.sh.in, then regenerate. Standalone at runtime.
# ==============================================================================
# apply-patches.sh — Automated Patch Installer for BBRv3 for crDroid sm8750 on crDroid 16.0
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PATCH_DIR="${SCRIPT_DIR}/patches"

MODE="apply"
DRY_RUN=0
ALLOW_DIRTY=0

usage() {
    local exit_code="${1:-0}"
    cat <<EOF
Usage: $(basename "$0") [OPTIONS] <ANDROID_BUILD_ROOT>

Applies or reverts the BBRv3 for crDroid sm8750 patch series to your crDroid 16.0 source tree.
Before anything is changed, the whole series is simulated on a temporary copy
of the affected files, so a patch is checked on top of the ones before it.

Options:
    -c, --check        Simulate the whole series without modifying any files.
    -r, --reverse      Revert previously applied patches (last patch first).
        --allow-dirty  Apply even if a target repository has uncommitted changes.
    -h, --help         Show this help message.

Arguments:
    <ANDROID_BUILD_ROOT>   Path to the root of your crDroid 16.0 source tree.

Exit codes:
    0  success                      3  aborted mid-way, tree partially changed
    1  usage error                  4  uncommitted changes in a target repository
    2  a patch does not apply

Examples:
    $(basename "$0") /media/Android/crdroid
    $(basename "$0") --check /media/Android/crdroid
    $(basename "$0") --reverse /media/Android/crdroid
EOF
    exit "${exit_code}"
}

# Parse options
while [[ $# -gt 0 ]]; do
    case "$1" in
        -c|--check)
            DRY_RUN=1
            shift
            ;;
        -r|--reverse)
            MODE="reverse"
            shift
            ;;
        --allow-dirty)
            ALLOW_DIRTY=1
            shift
            ;;
        -h|--help)
            usage 0
            ;;
        -*)
            echo "[-] Error: Unknown option: $1" >&2
            usage 1
            ;;
        *)
            break
            ;;
    esac
done

if [[ $# -lt 1 ]]; then
    echo "[-] Error: Missing ANDROID_BUILD_ROOT argument." >&2
    usage 1
fi

if [[ ! -d "$1" ]]; then
    echo "[-] Error: ANDROID_BUILD_ROOT is not a directory: $1" >&2
    exit 1
fi
ANDROID_ROOT="$(cd "$1" && pwd)"

# Module patches and their target repositories.
PATCHES=(
    "kernel/oneplus/sm8750:bbrv3-android15-6.6.patch:TCP BBRv3 Android15 Linux6.6"
)

# Empty requires every target; otherwise this one repository may be absent.
OPTIONAL_REPO=""

echo "===================================================================="
echo " BBRv3 for crDroid sm8750 Patch Tool [Mode: ${MODE^^}]"
echo " Android Root: ${ANDROID_ROOT}"
echo "===================================================================="

# Run order: as listed, or last-to-first when reverting.
ORDER=("${PATCHES[@]}")
if [[ "${MODE}" == "reverse" ]]; then
    ORDER=()
    for (( i=${#PATCHES[@]}-1; i>=0; i-- )); do
        ORDER+=("${PATCHES[i]}")
    done
fi

APPLY_ARGS=()
VERB="applied"
if [[ "${MODE}" == "reverse" ]]; then
    APPLY_ARGS+=(--reverse)
    VERB="reverted"
fi

# Target repositories in order of first use, each with its patches in run order.
REPOS=()
declare -A SERIES=()
declare -A DESC=()
for item in "${ORDER[@]}"; do
    IFS=":" read -r rel_repo patch_file desc <<< "$item"
    if [[ -z "${SERIES[${rel_repo}]+set}" ]]; then
        REPOS+=("${rel_repo}")
        SERIES[${rel_repo}]=""
    fi
    SERIES[${rel_repo}]+="${patch_file} "
    DESC[${patch_file}]="${desc}"
done

# Reference commits come from NOTICE — the same list the documentation shows.
reference_commit() {
    [[ -f "${SCRIPT_DIR}/NOTICE" ]] || return 0
    awk -v r="$1" '$1 == r && length($2) == 40 && $2 ~ /^[0-9a-f]+$/ { print $2; exit }' \
        "${SCRIPT_DIR}/NOTICE"
}

# How HEAD relates to the reference commit. Information only, never a reason to abort:
# the series may well apply to newer sources.
describe_reference() {
    local repo_dir="$1" ref="$2" head
    if ! head="$(git -C "${repo_dir}" rev-parse --verify -q HEAD)"; then
        echo "no commit checked out"
    elif [[ -z "${ref}" ]]; then
        echo "HEAD ${head:0:12}; no reference commit listed in NOTICE"
    elif [[ "${head}" == "${ref}" ]]; then
        echo "matches reference ${ref:0:12}"
    elif ! git -C "${repo_dir}" cat-file -e "${ref}^{commit}" 2>/dev/null; then
        echo "HEAD ${head:0:12}; reference ${ref:0:12} not in local history (older tree or another remote)"
    elif git -C "${repo_dir}" merge-base --is-ancestor "${ref}" "${head}"; then
        echo "HEAD ${head:0:12} is newer than reference ${ref:0:12}"
    else
        echo "HEAD ${head:0:12} does not contain reference ${ref:0:12}"
    fi
}

# True if the directory is the top of its own git repository (not just inside one).
is_own_git_repo() {
    local top
    top="$(git -C "$1" rev-parse --show-toplevel 2>/dev/null)" || return 1
    [[ "$(cd "${top}" && pwd -P)" == "$(cd "$1" && pwd -P)" ]]
}

# Runs a repository's patches one after another on a copy of the files they touch.
# A later patch is thereby checked on top of the earlier ones, and the real tree
# stays untouched. (`git apply --check a b` does not do this: it checks each patch
# against the original files.) Sets SIM_FAILED and SIM_OUTPUT on failure.
SANDBOX_ROOT="$(mktemp -d)"
trap 'rm -rf "${SANDBOX_ROOT}"' EXIT
SIM_COUNT=0
SIM_FAILED=""
SIM_OUTPUT=""
simulate_series() {
    local repo_dir="$1" patch_file path sandbox
    shift
    SIM_COUNT=$((SIM_COUNT + 1))
    sandbox="${SANDBOX_ROOT}/${SIM_COUNT}"
    git -c init.defaultBranch=sandbox init -q "${sandbox}"
    for patch_file in "$@"; do
        while IFS= read -r path; do
            if [[ -n "${path}" && -e "${repo_dir}/${path}" && ! -e "${sandbox}/${path}" ]]; then
                mkdir -p "$(dirname "${sandbox}/${path}")"
                cp -p "${repo_dir}/${path}" "${sandbox}/${path}"
            fi
        done < <(git apply --numstat "${PATCH_DIR}/${patch_file}" | cut -f3)
    done
    for patch_file in "$@"; do
        if ! SIM_OUTPUT="$(git -C "${sandbox}" apply "${APPLY_ARGS[@]}" "${PATCH_DIR}/${patch_file}" 2>&1)"; then
            SIM_FAILED="${patch_file}"
            return 1
        fi
    done
}

# Phase 1: check every target repository and simulate its series
echo ""
echo "[*] Phase 1: Checking target repositories and simulating the series..."

FAILED_CHECKS=0
DIRTY_REPOS=()

for rel_repo in "${REPOS[@]}"; do
    target_repo="${ANDROID_ROOT}/${rel_repo}"
    read -r -a series <<< "${SERIES[${rel_repo}]}"

    missing=0
    for patch_file in "${series[@]}"; do
        if [[ ! -f "${PATCH_DIR}/${patch_file}" ]]; then
            echo " [-] Patch file not found: ${PATCH_DIR}/${patch_file}" >&2
            missing=1
        fi
    done
    if [[ ${missing} -eq 1 ]]; then
        FAILED_CHECKS=$((FAILED_CHECKS + 1))
        continue
    fi

    if [[ ! -d "${target_repo}" ]]; then
        if [[ "${rel_repo}" == "${OPTIONAL_REPO}" ]]; then
            echo " [!] Note: Optional target '${rel_repo}' not found in tree (device-specific)."
        else
            echo " [-] Missing required target repository: ${rel_repo}" >&2
            FAILED_CHECKS=$((FAILED_CHECKS + 1))
        fi
        continue
    fi

    echo " [*] ${rel_repo}"
    if is_own_git_repo "${target_repo}"; then
        echo "     source: $(describe_reference "${target_repo}" "$(reference_commit "${rel_repo}")")"
        # Applying on top of unrelated local edits mixes them with this series.
        # Reverting is exempt: an applied series is itself an uncommitted change.
        if [[ "${MODE}" == "apply" && -n "$(git -C "${target_repo}" status --porcelain --untracked-files=no)" ]]; then
            DIRTY_REPOS+=("${rel_repo}")
            echo "     [!] uncommitted changes in this repository"
        fi
    else
        echo "     source: not a git repository of its own; reference and local-change checks skipped"
    fi

    if simulate_series "${target_repo}" "${series[@]}"; then
        for patch_file in "${series[@]}"; do
            echo "     [+] OK: ${patch_file} (${DESC[${patch_file}]})"
        done
    else
        echo "     [-] FAILED: ${SIM_FAILED} cannot be ${VERB} in ${rel_repo} (simulated in order: ${series[*]})" >&2
        # Show git's own reason (first lines only), e.g. "patch does not apply".
        printf '%s\n' "${SIM_OUTPUT}" | head -n 5 | sed 's/^/       /' >&2
        FAILED_CHECKS=$((FAILED_CHECKS + 1))
    fi
done

if [[ ${FAILED_CHECKS} -gt 0 ]]; then
    echo ""
    echo "[-] ABORTING: ${FAILED_CHECKS} target(s) failed the check. Nothing was changed." >&2
    echo "    Check if the patches are already applied or if your source tree diverged." >&2
    exit 2
fi

if [[ ${#DIRTY_REPOS[@]} -gt 0 ]]; then
    if [[ ${ALLOW_DIRTY} -eq 0 ]]; then
        echo ""
        echo "[-] ABORTING: uncommitted changes in these target repositories:" >&2
        printf '      %s\n' "${DIRTY_REPOS[@]}" >&2
        echo "    Commit or stash them first (git -C <repo> status), or rerun with" >&2
        echo "    --allow-dirty to put this series on top of your own changes." >&2
        exit 4
    fi
    echo " [!] --allow-dirty: continuing on top of uncommitted changes in: ${DIRTY_REPOS[*]}"
fi

if [[ ${DRY_RUN} -eq 1 ]]; then
    echo ""
    echo "[+] Dry-run check successful: the whole series can be ${VERB} (simulated on a copy, tree untouched)."
    exit 0
fi

# Phase 2: Apply / Reverse patches
echo ""
echo "[*] Phase 2: Executing [${MODE^^}]..."

DONE_LIST=()
for item in "${ORDER[@]}"; do
    IFS=":" read -r rel_repo patch_file _ <<< "$item"
    target_repo="${ANDROID_ROOT}/${rel_repo}"
    patch_path="${PATCH_DIR}/${patch_file}"

    if [[ ! -d "${target_repo}" && "${rel_repo}" == "${OPTIONAL_REPO}" ]]; then
        echo " [~] Skipping optional target: ${rel_repo}"
        continue
    fi

    if ! git -C "${target_repo}" apply "${APPLY_ARGS[@]}" "${patch_path}"; then
        echo "" >&2
        echo "[-] ABORTED: ${patch_file} failed on ${rel_repo} although the check passed." >&2
        if [[ ${#DONE_LIST[@]} -gt 0 ]]; then
            echo "    Already processed in this run (tree is now partially changed):" >&2
            printf '      %s\n' "${DONE_LIST[@]}" >&2
            echo "    Inspect with 'git -C <repo> status' and undo with 'git -C <repo> apply --reverse <patch>'." >&2
        fi
        exit 3
    fi
    DONE_LIST+=("${patch_file} -> ${rel_repo}")
    if [[ "${MODE}" == "reverse" ]]; then
        echo " [✓] Reverted: ${patch_file} from ${rel_repo}"
    else
        echo " [✓] Applied: ${patch_file} to ${rel_repo}"
    fi
done

echo ""
echo "===================================================================="
if [[ "${MODE}" == "reverse" ]]; then
    echo " [+] Reverted all BBRv3 for crDroid sm8750 patches."
else
    echo " [+] Applied all BBRv3 for crDroid sm8750 patches."
    echo "     Next: review 'git -C <repo> diff' in each target repository, then"
    echo "     build and validate on your device. A clean apply is not a working build."
fi
echo "===================================================================="
